#!/usr/bin/python3
""" this is a file for GitHub action,
an environment where I can run test suits in python
and ruby and other highlevel languages
together with my front endprojects """

import modules 
name: Deploy to Github Pages

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Build the app
      run: npm run build

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
